# permissions for end users to edit graphqlmeshes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: graphqlmesh-editor-role
rules:
- apiGroups:
  - mesh.graphql-mesh-operator.io
  resources:
  - graphqlmeshes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mesh.graphql-mesh-operator.io
  resources:
  - graphqlmeshes/status
  verbs:
  - get
