
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - gw.graphqlgw.io
  resources:
  - graphqlgateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gw.graphqlgw.io
  resources:
  - graphqlgateways/status
  verbs:
  - get
  - patch
  - update
