apiVersion: mesh.graphql-mesh-operator.io/v1alpha1
kind: DataSource
metadata:
  name: wiki
spec:
  type: openapi
  handlerConfig:
    source:  https://api.apis.guru/v2/specs/wikimedia.org/1.0.0/swagger.yaml

            